version: '3.9'

services:
  app:
    image: node:20
    command: sh -c "npm i && npm run start:dev"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on: 
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on: 
      - mongo